OPENQASM 2.0;
include "qelib1.inc";
qreg q[7];
qreg control[1];
creg c[8];
h control[0];
z control[0];
ry(pi/4) q[0];
ry(pi/4) q[1];
h q[2];
x q[3];
ccx control[0], q[0], q[1];
swap q[0], q[1];
ccx control[0], q[0], q[3];
swap q[0], q[3];
cx control[0], q[1];
measure q[1] -> c[1];
t q[0];
h q[2];
z q[5];
t q[1];
x q[2];
t q[6];
measure control[0] -> c[7];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
measure q[5] -> c[5];
measure q[6] -> c[6];
