measure q[8] -> early[8];
measure q[4] -> early[4];
measure q[2] -> early[2];
h q[1];
s q[6];
s q[0];
h q[2];
h q[5];
z q[2];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
measure q[5] -> c[5];
measure q[6] -> c[6];
measure q[7] -> c[7];
measure q[8] -> c[8];
