OPENQASM 2.0;
include "qelib1.inc";
qreg q[10];
qreg control[1];
creg c[11];
h control[0];
z control[0];
h q[0];
ry(pi/4) q[1];
x q[2];
x q[3];
cx control[0], q[0];
measure q[0] -> c[0];
z q[7];
h q[0];
t q[2];
t q[4];
s q[4];
measure control[0] -> c[10];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
measure q[5] -> c[5];
measure q[6] -> c[6];
measure q[7] -> c[7];
measure q[8] -> c[8];
measure q[9] -> c[9];
