measure q[0] -> early[0];
id q[1];
measure q[1] -> early[1];
measure q[2] -> early[2];
measure q[3] -> early[3];
id q[4];
measure q[4] -> early[4];
measure q[5] -> early[5];
id q[6];
measure q[6] -> early[6];
measure q[7] -> early[7];
h q[4];
rx(pi/4) q[3];
x q[4];
z q[6];
y q[5];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
measure q[5] -> c[5];
measure q[6] -> c[6];
measure q[7] -> c[7];
