OPENQASM 2.0;
include "qelib1.inc";
qreg q[4];
creg c[4];
creg early[4];
measure q[2] -> early[2];
id q[0];
measure q[0] -> early[0];
measure q[1] -> early[1];
measure q[3] -> early[3];
y q[0];
x q[2];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
