OPENQASM 2.0;
include "qelib1.inc";
qreg q[5];
creg c[5];
creg early[5];
measure q[4] -> early[4];
h q[0];
h q[0];
measure q[0] -> early[0];
measure q[1] -> early[1];
measure q[2] -> early[2];
measure q[3] -> early[3];
h q[2];
x q[1];
x q[4];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
