OPENQASM 2.0;
include "qelib1.inc";
qreg q[3];
creg c[3];
creg early[3];
measure q[0] -> early[0];
measure q[1] -> early[1];
h q[2];
h q[2];
measure q[2] -> early[2];
x q[2];
h q[2];
z q[2];
y q[2];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
