OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
qreg control[1];
creg c[3];
h control[0];
measure control[0] -> c[2];
ry(pi/4) q[0];
ry(pi/4) q[1];
cx control[0], q[1];
swap q[1], q[0];
cx control[0], q[1];
cx control[0], q[1];
swap q[1], q[0];
cx control[0], q[1];
cx control[0], q[0];
swap q[0], q[1];
cx control[0], q[0];
h q[1];
s q[1];
t q[0];
x q[1];
x q[1];
measure q[0] -> c[0];
measure q[1] -> c[1];
