OPENQASM 2.0;
include "qelib1.inc";
qreg q[3];
qreg control[1];
creg c[4];
h control[0];
x q[0];
x q[1];
h q[2];
ccx control[0], q[1], q[2];
swap q[1], q[2];
ccx control[0], q[1], q[0];
swap q[1], q[0];
ccx control[0], q[0], q[1];
swap q[0], q[1];
cx control[0], q[1];
measure q[1] -> c[1];
h q[2];
h q[0];
h q[1];
s q[2];
t q[2];
z q[0];
measure control[0] -> c[3];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
