OPENQASM 2.0;
include "qelib1.inc";
qreg q[6];
creg c[6];
creg early[6];
measure q[1] -> early[1];
measure q[0] -> early[0];
measure q[5] -> early[5];
t q[3];
t q[3];
z q[3];
s q[3];
s q[2];
z q[3];
t q[2];
z q[3];
x q[5];
z q[5];
rx(pi/4) q[4];
h q[0];
rx(pi/4) q[5];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
measure q[5] -> c[5];
