OPENQASM 2.0;
include "qelib1.inc";
qreg q[5];
qreg control[1];
creg c[6];
h control[0];
z control[0];
x q[0];
x q[1];
x q[2];
h q[3];
ccx control[0], q[3], q[1];
swap q[3], q[1];
ccx control[0], q[4], q[3];
swap q[4], q[3];
ccx control[0], q[0], q[2];
swap q[0], q[2];
ccx control[0], q[0], q[3];
swap q[0], q[3];
cx control[0], q[2];
measure q[2] -> c[2];
t q[3];
h q[0];
h q[2];
z q[3];
measure control[0] -> c[5];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
