OPENQASM 2.0;
include "qelib1.inc";
qreg q[6];
creg c[6];
creg early[6];
measure q[1] -> early[1];
measure q[4] -> early[4];
measure q[2] -> early[2];
s q[0];
x q[3];
x q[0];
h q[5];
x q[3];
z q[0];
s q[0];
h q[1];
y q[4];
z q[2];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
measure q[5] -> c[5];
