OPENQASM 2.0;
include "qelib1.inc";
qreg q[7];
qreg control[1];
creg c[8];
h control[0];
measure control[0] -> c[7];
h q[0];
ry(pi/4) q[1];
ry(pi/4) q[2];
h q[3];
cx control[0], q[1];
h q[2];
h q[3];
x q[2];
s q[5];
x q[1];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
measure q[5] -> c[5];
measure q[6] -> c[6];
