OPENQASM 2.0;
include "qelib1.inc";
qreg q[10];
qreg control[1];
creg c[11];
h control[0];
h q[0];
h q[1];
x q[2];
ry(pi/4) q[3];
cx control[0], q[2];
measure q[2] -> c[2];
cx control[0], q[6];
measure q[6] -> c[6];
cx control[0], q[4];
measure q[4] -> c[4];
cx control[0], q[1];
measure q[1] -> c[1];
cx control[0], q[9];
measure q[9] -> c[9];
z q[8];
z q[8];
s q[8];
measure control[0] -> c[10];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
measure q[5] -> c[5];
measure q[6] -> c[6];
measure q[7] -> c[7];
measure q[8] -> c[8];
measure q[9] -> c[9];
