measure q[9] -> early[9];
measure q[7] -> early[7];
id q[0];
measure q[0] -> early[0];
id q[1];
measure q[1] -> early[1];
id q[2];
measure q[2] -> early[2];
h q[3];
h q[3];
measure q[3] -> early[3];
h q[4];
h q[4];
measure q[4] -> early[4];
id q[5];
measure q[5] -> early[5];
h q[6];
h q[6];
measure q[6] -> early[6];
measure q[8] -> early[8];
id q[10];
measure q[10] -> early[10];
h q[9];
x q[6];
rx(pi/4) q[2];
z q[6];
x q[2];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
measure q[5] -> c[5];
measure q[6] -> c[6];
measure q[7] -> c[7];
measure q[8] -> c[8];
measure q[9] -> c[9];
measure q[10] -> c[10];
