h control[0];
x q[0];
x q[1];
ry(pi/4) q[2];
x q[3];
cx control[0], q[2];
measure q[2] -> c[2];
cx control[0], q[0];
measure q[0] -> c[0];
s q[2];
z q[3];
z q[1];
s q[2];
measure control[0] -> c[4];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
