ry(pi/2) control[0];
x q[0];
ry(pi/4) q[1];
x q[2];
ry(pi/4) q[3];
cx control[0], q[1];
measure q[1] -> c[1];
cx control[0], q[5];
measure q[5] -> c[5];
t q[1];
z q[1];
z q[0];
h q[1];
z q[5];
measure control[0] -> c[7];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
measure q[5] -> c[5];
measure q[6] -> c[6];
