h coin[0];
rccx coin[0],node[1],anc[0];
ccx node[2],anc[0],node[0];
rccx coin[0],node[1],anc[0];
ccx coin[0],node[2],node[1];
cx coin[0],node[2];
x coin[0];
x node[1];
rccx coin[0],node[1],anc[0];
x node[2];
ccx node[2],anc[0],node[0];
rccx coin[0],node[1],anc[0];
ccx coin[0],node[2],node[1];
cx coin[0],node[2];
u2(-pi,-pi) coin[0];
x node[1];
rccx coin[0],node[1],anc[0];
x node[2];
ccx node[2],anc[0],node[0];
rccx coin[0],node[1],anc[0];
ccx coin[0],node[2],node[1];
cx coin[0],node[2];
x coin[0];
x node[1];
rccx coin[0],node[1],anc[0];
x node[2];
ccx node[2],anc[0],node[0];
rccx coin[0],node[1],anc[0];
ccx coin[0],node[2],node[1];
cx coin[0],node[2];
u2(-pi,-pi) coin[0];
x node[1];
rccx coin[0],node[1],anc[0];
x node[2];
ccx node[2],anc[0],node[0];
rccx coin[0],node[1],anc[0];
ccx coin[0],node[2],node[1];
cx coin[0],node[2];
x coin[0];
x node[1];
rccx coin[0],node[1],anc[0];
x node[2];
ccx node[2],anc[0],node[0];
rccx coin[0],node[1],anc[0];
ccx coin[0],node[2],node[1];
cx coin[0],node[2];
x coin[0];
x node[1];
x node[2];
barrier node[0],node[1],node[2],coin[0],anc[0];
measure node[0] -> meas[0];
measure node[1] -> meas[1];
measure node[2] -> meas[2];
measure coin[0] -> meas[3];
measure anc[0] -> meas[4];
